kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bitwaden-bitwarden-0
  namespace: bitwarden
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
