apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden-pv
spec:
  capacity:
    storage: 25Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /openshift/bitwarden/
    server: 192.168.1.221
  persistentVolumeReclaimPolicy: Retain
