apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /small/openshift/unifi-dev
    server: 172.20.10.25
  persistentVolumeReclaimPolicy: Retain
