kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-pvc
  namespace: unifi
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 19Gi
