apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /openshift/unifi-dev
    server: 192.168.1.7
  persistentVolumeReclaimPolicy: Retain
