apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  creationTimestamp: "2021-07-13T23:32:10Z"
  generation: 2
  labels:
    app: home-assistant
  name: home-assistant
  namespace: hass
  resourceVersion: "115873048"
  uid: 04e67538-bef1-4536-9a6b-7c3810f2d0c9
spec:
  rules:
  - host: hass.r3d3mpt10n.com
    http:
      paths:
      - backend:
          service:
            name: home-assistant-web
            port:
              number: 8123
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
   - hass.r3d3mpt10n.com
    secretName: hass-cm-tls
