apiVersion: v1
kind: PersistentVolume
metadata:
  name: openstack-mysql-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
     namespace: openstack
     name: mariadb-openstack
  nfs: 
    path: /small/openshift/openstack-mysql
    server: 192.168.1.7
  persistentVolumeReclaimPolicy: Retain
