apiVersion: v1
kind: PersistentVolume
metadata:
  name: openstack-mysql-cell-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: openstack
    name: mariadb-openstack-cell1
  nfs:
    path: /small/openshift/openstack-mysql-cell
    server: 192.168.1.7
  persistentVolumeReclaimPolicy: Retain
