apiVersion: v1
kind: PersistentVolume
metadata:
  name: openstack-ovnsb-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  claimRef:
     namespace: openstack
     name: ovndbcluster-sb-etc-ovn-ovsdbserver-sb-0
  nfs: 
    path: /small/openshift/openstack-ovn-sb
    server: 192.168.1.7
  persistentVolumeReclaimPolicy: Retain
