apiVersion: v1
kind: PersistentVolume
metadata:
  name: openstack-rmq-cell
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: openstack
    name: persistence-rabbitmq-cell1-server-0
  nfs:
    path: /small/openshift/openstack-rmq-cell
    server: 192.168.1.7
  persistentVolumeReclaimPolicy: Retain
