apiVersion: v1
kind: PersistentVolume
metadata:
  name: openstack-glance
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  claimRef:
     namespace: openstack
     name: glance
  nfs: 
    path: /small/openshift/openstack-glance
    server: 192.168.1.7
  persistentVolumeReclaimPolicy: Retain
