apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempmon
  namespace: homemon
  labels:
    app: tempmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempmon
  template:
    metadata:
      labels:
        app: tempmon
    spec:
      containers:
      - name: tempmon
        image: "registry.gitlab.com/shep03/homemonproject/python3-bme-sensor:v1.0.0"
        volumeMounts:
        - name: shared-data
          mountPath: /data
        securityContext:
          runAsUser: 0
          privileged: true
      - name: go-exporter
        image: "registry.gitlab.com/shep03/homemonproject/go-metrics-exporter:v1.0.0"
        volumeMounts:
        - name: shared-data
          mountPath: /data
        ports:
        - containerPort: 9100
          name: prom-9100
          protocol: TCP
        securityContext:
          runAsUser: 0
          privileged: true          
      volumes:
      - name: shared-data
        emptyDir: {}
      nodeSelector:
        kubernetes.io/arch: arm64
