apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: tempmon
  name: temp-exporter
spec:
  selector:
    app: tempmon
  ports:
    - name: go-exporter
      protocol: TCP
      port: 8080
      targetPort: 8080
