apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: hass
  labels:
    app: home-assistant
    version: v0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      name: home-assistant
      labels:
        app: home-assistant
    spec:
      serviceAccountName: hass
      containers:
      - name: home-assistant
        image: "docker.io/homeassistant/home-assistant:latest"
        env:
        - name: TZ
          value: "Australia/Brisbane"
        ports:
        - containerPort: 8123
          name: hass-web
          protocol: TCP
        volumeMounts:
        - mountPath: "/config"
          name: hass-config
      volumes:
      - name: hass-config
        persistentVolumeClaim:
          claimName: hass-pvc
      nodeSelector:
        kubernetes.io/arch: amd64
