apiVersion: v1
kind: PersistentVolume
metadata:
  name: hass-data-pv
spec:
  capacity:
    storage: 70Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /small/openshift/hass
    server: 192.168.1.7
  persistentVolumeReclaimPolicy: Retain
