apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data-pv
spec:
  capacity:
    storage: 30Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /small/openshift/mosquitto-data
    server: 172.20.10.25
  persistentVolumeReclaimPolicy: Retain
