apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /small/openshift/mosquitto
    server: 192.168.1.7
  persistentVolumeReclaimPolicy: Retain
